name: Add tar.gz to release

# Controls when the workflow will run
on:
  # Triggers the workflow on new releases
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        id: pack
        run: |
          sed -i 's/: "git",/: "'${GITHUB_REF:10}'",/' extension.json
          cd $GITHUB_WORKSPACE/..
          tar -cvzf NSFWTag-${GITHUB_REF:10}.tar.gz --exclude='.git*' $(basename $GITHUB_WORKSPACE)
          echo "::set-output name=file::$PWD/NSFWTag-${GITHUB_REF:10}.tar.gz"
      
      - name: Add asset to release
        uses: djn24/add-asset-to-release@v1
        with:
          # GitHub token with permission to upload.
          token: ${{ github.token }}
          # File to upload.
          path: ${{ steps.pack.outputs.file }}
